name: Fix Railway Deployment

on:
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Railway backend URL'
        default: 'https://tez-social-production.up.railway.app'
        required: false
        type: string

jobs:
  diagnose-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Diagnose backend issue
        id: diagnose
        run: |
          BACKEND_URL="${{ github.event.inputs.backend_url }}"
          if [ -z "$BACKEND_URL" ]; then
            BACKEND_URL="https://tez-social-production.up.railway.app"
          fi
          
          echo "Diagnosing backend at $BACKEND_URL"
          
          # Check basic connectivity
          BACKEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BACKEND_URL || echo "failed")
          echo "Backend status code: $BACKEND_STATUS"
          
          # Try to access the API
          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BACKEND_URL/api/health || echo "failed")
          AUTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BACKEND_URL/api/auth/login || echo "failed")
          
          echo "Health endpoint status: $HEALTH_STATUS"
          echo "Auth endpoint status: $AUTH_STATUS"
          
          # Determine issue type based on response codes
          if [ "$BACKEND_STATUS" == "failed" ]; then
            echo "error_type=connectivity" >> $GITHUB_OUTPUT
          elif [ "$BACKEND_STATUS" == "502" ] || [ "$BACKEND_STATUS" == "503" ]; then
            echo "error_type=service_unavailable" >> $GITHUB_OUTPUT
          elif [ "$BACKEND_STATUS" == "404" ]; then
            echo "error_type=not_found" >> $GITHUB_OUTPUT
          elif [ "$HEALTH_STATUS" == "404" ] && [ "$AUTH_STATUS" != "404" ]; then
            echo "error_type=missing_health_endpoint" >> $GITHUB_OUTPUT
          elif [ "$AUTH_STATUS" == "404" ] && [ "$HEALTH_STATUS" != "404" ]; then
            echo "error_type=missing_auth_endpoint" >> $GITHUB_OUTPUT
          elif [ "$BACKEND_STATUS" != "200" ] && [ "$HEALTH_STATUS" != "200" ] && [ "$AUTH_STATUS" != "200" ]; then
            echo "error_type=api_error" >> $GITHUB_OUTPUT
          else
            echo "error_type=unknown" >> $GITHUB_OUTPUT
          fi
          
          # Write diagnosis to summary
          echo "## Backend Diagnosis" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Endpoint Status" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend URL**: $BACKEND_URL" >> $GITHUB_STEP_SUMMARY
          echo "- **Main endpoint**: HTTP $BACKEND_STATUS" >> $GITHUB_STEP_SUMMARY
          echo "- **Health endpoint**: HTTP $HEALTH_STATUS" >> $GITHUB_STEP_SUMMARY
          echo "- **Auth endpoint**: HTTP $AUTH_STATUS" >> $GITHUB_STEP_SUMMARY

      - name: Add health endpoint if missing
        if: steps.diagnose.outputs.error_type == 'missing_health_endpoint'
        run: |
          echo "Adding health endpoint to backend"
          
          # Create health controller
          mkdir -p backend/src/health
          
          # Create health controller file
          cat > backend/src/health/health.controller.ts << 'EOF'
          import { Controller, Get } from '@nestjs/common';
          
          @Controller('health')
          export class HealthController {
            @Get()
            getHealth() {
              return {
                status: 'ok',
                timestamp: new Date().toISOString(),
                uptime: process.uptime(),
              };
            }
          }
          EOF
          
          # Update app module to include health controller
          sed -i '/import { AppController } from/a import { HealthController } from '\''./health/health.controller'\'';' backend/src/app.module.ts
          sed -i '/controllers: \[AppController/s/AppController/AppController, HealthController/' backend/src/app.module.ts
          
          git add backend/src/health/health.controller.ts backend/src/app.module.ts
          git commit -m "fix: add health endpoint to backend"

      - name: Fix connectivity issues
        if: steps.diagnose.outputs.error_type == 'connectivity' || steps.diagnose.outputs.error_type == 'service_unavailable'
        run: |
          echo "Fixing backend connectivity issues"
          
          # Check main.ts for correct port configuration
          if grep -q "const port = process.env.PORT" backend/src/main.ts; then
            echo "Port configuration looks good"
          else
            echo "Updating port configuration in main.ts"
            sed -i 's/await app.listen([0-9]*)/await app.listen(process.env.PORT || 3000)/' backend/src/main.ts
            git add backend/src/main.ts
            git commit -m "fix: use environment PORT variable for backend"
          fi
          
          # Ensure CORS is properly configured
          if grep -q "app.enableCors()" backend/src/main.ts; then
            echo "CORS is already enabled"
          else
            echo "Enabling CORS in main.ts"
            sed -i '/const app = await NestFactory/a \  app.enableCors();' backend/src/main.ts
            git add backend/src/main.ts
            git commit -m "fix: enable CORS for backend API"
          fi
          
          # Check for package.json start script
          if grep -q '"start": "node dist/main.js"' backend/package.json; then
            echo "Start script looks good"
          else
            echo "Updating start script in package.json"
            sed -i 's/"start": ".*"/"start": "node dist\/main.js"/' backend/package.json
            git add backend/package.json
            git commit -m "fix: update start script in package.json"
          fi

      - name: Fix route issues
        if: steps.diagnose.outputs.error_type == 'not_found' || steps.diagnose.outputs.error_type == 'missing_auth_endpoint'
        run: |
          echo "Fixing backend route issues"
          
          # Check if app module includes auth module
          if grep -q "AuthModule" backend/src/app.module.ts; then
            echo "Auth module is included in app module"
          else
            echo "Auth module might be missing, checking directory"
            if [ -d "backend/src/auth" ]; then
              echo "Auth directory exists, adding auth module to app module"
              sed -i '/import { AppController } from/a import { AuthModule } from '\''./auth/auth.module'\'';' backend/src/app.module.ts
              sed -i '/imports: \[/a \ \ \ \ AuthModule,' backend/src/app.module.ts
              git add backend/src/app.module.ts
              git commit -m "fix: include auth module in app module"
            else
              echo "Auth directory doesn't exist, creating minimal auth module"
              mkdir -p backend/src/auth
              
              # Create auth module
              cat > backend/src/auth/auth.module.ts << 'EOF'
              import { Module } from '@nestjs/common';
              import { AuthController } from './auth.controller';
              import { AuthService } from './auth.service';
              
              @Module({
                controllers: [AuthController],
                providers: [AuthService],
                exports: [AuthService],
              })
              export class AuthModule {}
              EOF
              
              # Create auth controller with login endpoint
              cat > backend/src/auth/auth.controller.ts << 'EOF'
              import { Controller, Post, Body } from '@nestjs/common';
              import { AuthService } from './auth.service';
              
              @Controller('auth')
              export class AuthController {
                constructor(private readonly authService: AuthService) {}
                
                @Post('login')
                async login(@Body() loginDto: any) {
                  return { message: 'Login endpoint active' };
                }
              }
              EOF
              
              # Create auth service
              cat > backend/src/auth/auth.service.ts << 'EOF'
              import { Injectable } from '@nestjs/common';
              
              @Injectable()
              export class AuthService {}
              EOF
              
              # Update app module
              sed -i '/import { AppController } from/a import { AuthModule } from '\''./auth/auth.module'\'';' backend/src/app.module.ts
              sed -i '/imports: \[/a \ \ \ \ AuthModule,' backend/src/app.module.ts
              
              git add backend/src/auth backend/src/app.module.ts
              git commit -m "fix: add minimal auth module with login endpoint"
            fi
          fi
          
          # Check global prefix in main.ts
          if grep -q "app.setGlobalPrefix" backend/src/main.ts; then
            echo "Global API prefix is set"
          else
            echo "Setting global API prefix in main.ts"
            sed -i '/const app = await NestFactory/a \  app.setGlobalPrefix('\''api'\'');' backend/src/main.ts
            git add backend/src/main.ts
            git commit -m "fix: set global API prefix to /api"
          fi

      - name: Fix API errors
        if: steps.diagnose.outputs.error_type == 'api_error' || steps.diagnose.outputs.error_type == 'unknown'
        run: |
          echo "Fixing general API errors"
          
          # Check for MongoDB connection in main app module
          if grep -q "MongooseModule.forRoot" backend/src/app.module.ts; then
            echo "MongoDB connection is configured"
            
            # Update MongoDB connection to use environment variable
            sed -i 's/MongooseModule.forRoot([^)]*)/MongooseModule.forRoot(process.env.MONGODB_URI || '\''mongodb:\/\/localhost\/tez-social'\'')/' backend/src/app.module.ts
            git add backend/src/app.module.ts
            git commit -m "fix: use environment variable for MongoDB connection" || echo "No changes to commit"
          else
            echo "MongoDB connection might be missing"
          fi
          
          # Add exception filters for better error handling
          if [ ! -f "backend/src/common/filters/all-exceptions.filter.ts" ]; then
            echo "Adding global exception filter"
            mkdir -p backend/src/common/filters
            
            cat > backend/src/common/filters/all-exceptions.filter.ts << 'EOF'
            import { ArgumentsHost, Catch, ExceptionFilter, HttpException, HttpStatus } from '@nestjs/common';
            import { Request, Response } from 'express';
            
            @Catch()
            export class AllExceptionsFilter implements ExceptionFilter {
              catch(exception: any, host: ArgumentsHost) {
                const ctx = host.switchToHttp();
                const response = ctx.getResponse<Response>();
                const request = ctx.getRequest<Request>();
                
                const status =
                  exception instanceof HttpException
                    ? exception.getStatus()
                    : HttpStatus.INTERNAL_SERVER_ERROR;
                
                const message =
                  exception instanceof HttpException
                    ? exception.message
                    : 'Internal server error';
                
                const responseBody = {
                  statusCode: status,
                  timestamp: new Date().toISOString(),
                  path: request.url,
                  method: request.method,
                  message: message,
                };
                
                console.error(`[Error] ${request.method} ${request.url}:`, exception);
                
                response.status(status).json(responseBody);
              }
            }
            EOF
            
            # Add filter to main.ts
            sed -i '/import { NestFactory } from/a import { AllExceptionsFilter } from '\''./common/filters/all-exceptions.filter'\'';' backend/src/main.ts
            sed -i '/app.enableCors()/a \  app.useGlobalFilters(new AllExceptionsFilter());' backend/src/main.ts || sed -i '/const app = await NestFactory/a \  app.useGlobalFilters(new AllExceptionsFilter());' backend/src/main.ts
            
            git add backend/src/common/filters/all-exceptions.filter.ts backend/src/main.ts
            git commit -m "fix: add global exception filter for better error handling"
          fi

      - name: Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git push
          
      - name: Update summary with fix details
        run: |
          ERROR_TYPE="${{ steps.diagnose.outputs.error_type }}"
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Applied Fixes" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          case "$ERROR_TYPE" in
            connectivity|service_unavailable)
              echo "- Updated port configuration to use environment variables" >> $GITHUB_STEP_SUMMARY
              echo "- Enabled CORS to allow cross-origin requests" >> $GITHUB_STEP_SUMMARY
              echo "- Updated start script in package.json" >> $GITHUB_STEP_SUMMARY
              ;;
              
            not_found|missing_auth_endpoint)
              echo "- Added auth module with login endpoint" >> $GITHUB_STEP_SUMMARY
              echo "- Set global API prefix to /api" >> $GITHUB_STEP_SUMMARY
              ;;
              
            missing_health_endpoint)
              echo "- Added health endpoint to backend" >> $GITHUB_STEP_SUMMARY
              ;;
              
            api_error|unknown)
              echo "- Updated MongoDB connection to use environment variables" >> $GITHUB_STEP_SUMMARY
              echo "- Added global exception filter for better error handling" >> $GITHUB_STEP_SUMMARY
              ;;
          esac
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "These changes have been committed and pushed. Railway should automatically pick up these changes and redeploy the backend. The deployment monitor will check the status again soon." >> $GITHUB_STEP_SUMMARY 