name: Launch Deployment Check

on:
  # Run on every push to main
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      check_type:
        description: 'Type of check to perform'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - vercel
          - railway

jobs:
  trigger-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for deployment
        run: |
          echo "Waiting 3 minutes for deployments to complete..."
          sleep 180

      - name: Trigger deployment monitor
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deployment-monitor.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |-
            {
              "check_type": "${{ github.event.inputs.check_type || 'all' }}"
            } 